### ISSUE TITLE
`docsify serve` monitors all path contents, including node_modules

### ISSUE THREAD

**Issue by KimBurgess** [QingWei-Li/docsify-cli#16]
When running `doscify serve <path>` live-reload sets up a file watch for the entire subtree of the path passed in. If a project is using NPM / yarn for package management (and index.html) is in the project root this results in the entire content of node_modules being monitored for file changes. Under some environments (i.e. dependencies containing a high number of *.md files) this will result in an ENOSPC error due to the number of individual files being watched.

It may be worth adding an exclusion for `node_modules/` to help prevent this.

I'll shoot through a PR later for you to consider - just noting this down before I forget :)

**Comment by QingWei-Li** [comment]
PRs welcome
