### ISSUE TITLE
[Feature request] Generate a static site using `docsify build` 

### ISSUE THREAD

**Issue by DethAriel** [QingWei-Li/docsify-cli#29]
To start with, thx for your package, good job!

In terms of improvements, it would be great if `docsify build` could generate a bunch of `.html`/`.css`/`.js` files that could be simply dumped into a webserver and behave as a static website.

**Comment by QingWei-Li** [comment]
GitBook is recommended if you need to build static files.

**Comment by QingWei-Li** [comment]
Duplicate of https://github.com/QingWei-Li/docsify/issues/136

**Comment by yhhwpp** [comment]
waiting..

**Comment by stoufa** [comment]
Is this feature built yet ?
I'm not a JS dev but I believe that `docsify build` will be similar to `docsify serve` with the exception of saving the result to files instead of just serving them temporarily.

**Comment by pitometsyurii** [comment]
Is that feature available? I can't use serve command instead I want to have js/html/css exported.

**Comment by MichaelCurrin** [comment]
No - see above. This is a duplicate of still open #136
