### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by xiaobo1234** [QingWei-Li/docsify-cli#30]
感觉这个项目只是命令行，最终的文档生成逻辑代码还是在 [docsify 项目](https://github.com/QingWei-Li/docsify)中。但是 [docsify 项目](https://github.com/QingWei-Li/docsify) 最近版本中已经修改的一些 bug，在使用这里的命令行时，还是错误的，不知道要怎么对接到新版本的 [docsify 项目](https://github.com/QingWei-Li/docsify)。PS：初次接触这方面的东西，心有余，力不足 -_-

**Comment by QingWei-Li** [comment]
卸载重装
